theme: jekyll-theme-minimal
title: CSP Final Website
description: My final project for AP Computer Science Principles. I am creating a GitHub Pages site using Jekyll
nav:
  - 'theme.md'
  - 'instagram.md'
  - 'discord.md'
  - 'snapchat.md'
